version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Host 8080 -> Container 8080
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PostgreSqlConnection=Host=postgres;Port=5432;Database=dbExample;Username=postgres;Password=29051453

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 29051453
      POSTGRES_DB: dbExample
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
